
    create table alimentazione (
        id_alimentazione integer generated by default as identity,
        tipo_carburante varchar(255),
        primary key (id_alimentazione)
    );

    create table bici (
        id_bici integer generated by default as identity,
        id_sospensione integer,
        id_veicolo integer unique,
        numero_marche integer not null,
        pieghevole boolean not null,
        primary key (id_bici)
    );

    create table categoria (
        id_categoria integer generated by default as identity,
        nome_categoria varchar(255),
        primary key (id_categoria)
    );

    create table colore (
        id_colore integer generated by default as identity,
        tipo_colore varchar(255),
        primary key (id_colore)
    );

    create table macchina (
        cilindrata integer not null,
        id_macchina integer generated by default as identity,
        id_veicolo integer unique,
        numero_porte integer not null,
        targa varchar(255),
        primary key (id_macchina)
    );

    create table marca (
        anno_fondazione integer not null,
        id_marca integer generated by default as identity,
        nazione varchar(255),
        nome_marca varchar(255),
        primary key (id_marca)
    );

    create table moto (
        cilindrata integer not null,
        id_moto integer generated by default as identity,
        id_veicolo integer unique,
        targa varchar(255),
        primary key (id_moto)
    );

    create table sospensione (
        id_sospensione integer generated by default as identity,
        marca_sospensione varchar(255),
        materiale varchar(255),
        tipo_sospensione varchar(255),
        primary key (id_sospensione)
    );

    create table veicolo (
        anno_produzione integer not null,
        data_aggiornamento date,
        data_inserimento date,
        id_alimentazione integer not null,
        id_categoria integer not null,
        id_colore integer not null,
        id_marca integer not null,
        id_veicolo integer generated by default as identity,
        modello varchar(255),
        primary key (id_veicolo)
    );

    alter table if exists bici 
       add constraint FK20w9irhi2ejvwwsnhd7mj8pwl 
       foreign key (id_sospensione) 
       references sospensione;

    alter table if exists bici 
       add constraint FKswktcdeh5uuwbhf8ducphchxo 
       foreign key (id_veicolo) 
       references veicolo;

    alter table if exists macchina 
       add constraint FKktm44xfs8hvv5evg3gdfq50u3 
       foreign key (id_veicolo) 
       references veicolo;

    alter table if exists moto 
       add constraint FK45syifcllae09quumt3uhcckk 
       foreign key (id_veicolo) 
       references veicolo;

    alter table if exists veicolo 
       add constraint FKmulkx4clibsa9a7v0hkv33yq2 
       foreign key (id_alimentazione) 
       references alimentazione;

    alter table if exists veicolo 
       add constraint FKadjynej4kplqqaia8h3t3w5m7 
       foreign key (id_categoria) 
       references categoria;

    alter table if exists veicolo 
       add constraint FK1c8wuj83gmqgnjcyerakq2vge 
       foreign key (id_colore) 
       references colore;

    alter table if exists veicolo 
       add constraint FKl2uxral8sefwlju24c4sx1fmw 
       foreign key (id_marca) 
       references marca;
