create table alimentazione 
(
    id_alimentazione integer generated by default as identity,
    tipo_carburante varchar(255),
    primary key (id_alimentazione)
);

insert into alimentazione (tipo_carburante) 
values ('Benzina'),
	   ('Diesel'), 
       ('Elettrica'),
       ('GPL'),
       ('Ibrida');

-------------------------------------------------------------------------------------------

create table bici 
(
    id_bici integer generated by default as identity,
    id_veicolo integer unique,
    id_sospensione integer,
    numero_marche integer not null,
    pieghevole boolean not null,
    primary key (id_bici)
);

insert into bici (id_veicolo, id_sospensione, numero_marche, pieghevole)
values (1, 1, 7, true);

-------------------------------------------------------------------------------------------

create table categoria 
(
    id_categoria integer generated by default as identity,
    nome_categoria varchar(255),
    primary key (id_categoria)
);

insert into categoria (nome_categoria)
values ('Utilitaria'),
	   ('SUV'),
       ('Sportiva')

-------------------------------------------------------------------------------------------

create table colore 
(
    id_colore integer generated by default as identity,
    tipo_colore varchar(255),
    primary key (id_colore)
);

insert into colore (tipo_colore) 
values ('Rosso'),
       ('Blu'),
       ('Nero'),
       ('Bianco'),
       ('Verde');

-------------------------------------------------------------------------------------------

create table macchina 
(
    id_macchina integer generated by default as identity,
    id_veicolo integer unique,
    cilindrata integer not null,
    numero_porte integer not null,
    targa varchar(255) not null unique,
    primary key (id_macchina)
);

insert into macchina (id_veicolo, cilindrata, numero_porte, targa)
values (1, 1200, 5, 'AB123CD');

-------------------------------------------------------------------------------------------

create table marca 
(
    id_marca integer generated by default as identity,
    anno_fondazione integer not null,
    nazione varchar(255),
    nome_marca varchar(255),
    primary key (id_marca)
);

insert into marca (anno_fondazione, nazione, nome_marca) 
values (1899, 'Italia', 'Fiat'),
       (1916, 'Italia', 'Ducati'),
       (1937, 'Germania', 'Volkswagen'),
       (1933, 'Francia', 'Renault'),
       (1926, 'Svizzera', 'BMC');

-------------------------------------------------------------------------------------------

create table moto 
(
    id_moto integer generated by default as identity,
    id_veicolo integer unique,
    cilindrata integer not null,
    targa varchar(255) not null unique,
    primary key (id_moto)
);

insert into moto (id_veicolo, cilindrata, targa)
values (1, 800, 'XY987ZT');

-------------------------------------------------------------------------------------------

create table sospensione
(
    id_sospensione integer generated by default as identity,
    marca_sospensione varchar(255),
    materiale varchar(255),
    tipo_sospensione varchar(255),
    primary key (id_sospensione)
);

insert into sospensione (marca_sospensione, materiale, tipo_sospensione) 
values ('RockShox', 'Alluminio', 'Idraulica'),
	   ('Fox', 'Carbonio', 'Molla'),
       ('Suntour', 'Acciaio', 'Aria'),
       ('Marzocchi', 'Titanio', 'Molla'),
       ('DT Swiss', 'Carbonio', 'Idraulica');

-------------------------------------------------------------------------------------------

create table veicolo 
(
    id_veicolo integer generated by default as identity,
    id_alimentazione integer not null,
    id_categoria integer not null,
    id_colore integer not null,
    id_marca integer not null,
    anno_produzione integer not null,
    data_aggiornamento date,
    data_inserimento date,
    modello varchar(255),
    primary key (id_veicolo)
);

insert into veicolo (id_alimentazione, id_categoria, id_colore, id_marca, anno_produzione, data_inserimento, data_aggiornamento, modello)
values (1, 1, 1, 1, 2020, '2025-03-02', '2025-07-21', 'Panda'),
       (2, 2, 2, 2, 2021, '2025-04-01', '2025-07-21', 'X5'),
       (3, 3, 3, 3, 2022, '2025-05-01', '2025-07-21', 'ID.4');

-------------------------------------------------------------------------------------------

alter table if exists bici 
   add constraint FK20w9irhi2ejvwwsnhd7mj8pwl 
   foreign key (id_sospensione) 
   references sospensione;

alter table if exists bici 
    add constraint FKswktcdeh5uuwbhf8ducphchxo 
    foreign key (id_veicolo) 
    references veicolo;

alter table if exists macchina 
    add constraint FKktm44xfs8hvv5evg3gdfq50u3 
    foreign key (id_veicolo) 
    references veicolo;

alter table if exists moto 
    add constraint FK45syifcllae09quumt3uhcckk 
    foreign key (id_veicolo) 
    references veicolo;

alter table if exists veicolo 
   add constraint FKmulkx4clibsa9a7v0hkv33yq2 
   foreign key (id_alimentazione) 
   references alimentazione;

alter table if exists veicolo 
   add constraint FKadjynej4kplqqaia8h3t3w5m7 
   foreign key (id_categoria) 
   references categoria;

alter table if exists veicolo 
   add constraint FK1c8wuj83gmqgnjcyerakq2vge 
   foreign key (id_colore) 
   references colore;

alter table if exists veicolo 
   add constraint FKl2uxral8sefwlju24c4sx1fmw 
   foreign key (id_marca) 
   references marca;